# Generated by Django 3.1.6 on 2021-08-03 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoreGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='frontend/static/images/loregroup/')),
            ],
        ),
        migrations.CreateModel(
            name='LoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=50)),
                ('quoter', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoreUndergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='frontend/static/images/loreundergroup/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loregroup')),
            ],
        ),
        migrations.AddField(
            model_name='loregroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loretype'),
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='frontend/static/images/lore/')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loregroup')),
                ('loretype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loretype')),
                ('undergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loreundergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fantasyclass', models.CharField(max_length=50)),
                ('lvl', models.IntegerField()),
                ('info', models.TextField(max_length=10000)),
                ('info2', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
