# Generated by Django 3.1.6 on 2021-08-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_hero_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, upload_to='frontend/static/images/hero/'),
        ),
    ]
